apiVersion: apps/v1
kind: Deployment
metadata:
  name: ast
  namespace: production
  labels:
    component: asterisk
spec:
  replicas: 2
  selector:
    matchLabels:
      component: asterisk
  template:
    metadata:
      labels:
        component: asterisk
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      terminationGracePeriodSeconds: 2700
      volumes:
        - name: google-service-account
          secret:
            secretName: google-service-account
        - name: astdb
          emptyDir:
            medium: Memory
            sizeLimit: "1Gi"
        - name: pjsip
          emptyDir:
            medium: Memory
            sizeLimit: "1Gi"
        - name: pbx
          emptyDir: {}
        - name: spool
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: logs
          emptyDir: {}
      initContainers:
        - name: init
          image: ghcr.io/voxoco/asterisk:latest
          command: ["bash", "-c", "mkdir -p /var/log/asterisk/cel-custom /var/spool/asterisk/monitor /var/spool/asterisk/meetme /var/spool/asterisk/voicemail && touch /etc/asterisk/pjsip.d/test.conf"]
          volumeMounts:
            - name: logs
              mountPath: /var/log/asterisk
            - name: spool
              mountPath: /var/spool/asterisk
            - name: pjsip
              mountPath: /etc/asterisk/pjsip.d
      containers:
        - name: asterisk-sidecar
          image: ghcr.io/voxoco/asterisk-sidecar:latest
          resources:
            requests:
              cpu: 200m
          ports:
            - containerPort: 4377
            - containerPort: 4573
          env:
            - name: TZ
              value: America/Chicago
            - name: KAMHOST
              value: kamailio-dmq
            - name: KAMSERVERID
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: serverId
            - name: NATSSERVERS
              value: "nats://nats-svc:4222"
            - name: NATSTOKEN
              valueFrom:
                secretKeyRef:
                  name: nats-token
                  key: key
            - name: MYSQL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
            - name: GCLOUD_MYSQL
              valueFrom:
                secretKeyRef:
                  name: gcloud-mysql-url
                  key: connectionString
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: clusterName
            - name: CONSUL_HTTP_ADDR
              valueFrom:
                secretKeyRef:
                  name: consul-address
                  key: key
            - name: CONSUL_HTTP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: consul-token
                  key: key
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
          volumeMounts:
            - name: logs
              mountPath: /var/log/asterisk
            - name: pbx
              mountPath: /var/lib/asterisk/sounds/pbx
            - name: spool
              mountPath: /var/spool/asterisk
            - name: tmp
              mountPath: /tmp
            - name: google-service-account
              mountPath: /var/secrets/google
            - name: pjsip
              mountPath: /etc/asterisk/pjsip.d
          imagePullPolicy: Always
        - name: presence
          image: ghcr.io/voxoco/presence:latest
          resources:
            requests:
              cpu: 100m
          ports:
            - name: http
              protocol: TCP
              containerPort: 9102
          env:
            - name: TZ
              value: America/Chicago
            - name: NATSSERVERS
              value: "nats://nats-svc:4222"
            - name: NATSTOKEN
              valueFrom:
                secretKeyRef:
                  name: nats-token
                  key: key
            - name: MYSQL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
            - name: GCLOUD_MYSQL
              valueFrom:
                secretKeyRef:
                  name: gcloud-mysql-url
                  key: connectionString
          imagePullPolicy: Always
        - name: asterisk
          image: ghcr.io/voxoco/asterisk:latest
          resources:
            requests:
              cpu: 1000m
          ports:
            - containerPort: 5080
          lifecycle:
            preStop:
              exec:
                command: [ "/var/lib/asterisk/gracefulShutdown.sh" ]
          env:
            - name: TZ
              value: America/Chicago
            - name: MYSQL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: astdb
              mountPath: /var/lib/asterisk/astdb
            - name: logs
              mountPath: /var/log/asterisk
            - name: pbx
              mountPath: /var/lib/asterisk/sounds/pbx
            - name: spool
              mountPath: /var/spool/asterisk
            - name: tmp
              mountPath: /tmp
            - name: pjsip
              mountPath: /etc/asterisk/pjsip.d
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
