apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: omnia-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: omnia-api
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 90