apiVersion: apps/v1
kind: Deployment
metadata:
  name: nqlite
  namespace: production
  labels:
    app: nqlite
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nqlite
  template:
    metadata:
      name: nqlite
      labels:
        app: nqlite
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      terminationGracePeriodSeconds: 2
      containers:
        - name: nqlite
          image: voxo/nqlite:latest
          args:
            - --nats-host=nats://nats-svc:4222
            - --token=$(TOKEN)
            - --external-backup=http
            - --external-backup-url=https://r2-worker.voxo.workers.dev/r2/nqlite_backup/nqlite.db?apiKey=$(R2_WORKER_API_KEY)
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: nats-token
                  key: key
            - name: R2_WORKER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: r2-worker-api-key
                  key: key
          ports:
            - containerPort: 4001
              name: http
          livenessProbe:
            httpGet:
              path: /health
              port: 4001
          startupProbe:
            httpGet:
              path: /health
              port: 4001
          imagePullPolicy: Always
