apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-gke
  namespace: production
  annotations:
    prometheus.io/port: '9102'
  labels:
    component: prometheus-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      component: prometheus-gke
  template:
    metadata:
      labels:
        component: prometheus-gke
    spec:
      volumes:
        - name: config
          configMap:
            name: prometheus-gke
        - name: google-service-account
          secret:
            secretName: google-service-account
      serviceAccount: manager
      containers:
        - name: prometheus-gke
          image: gke.gcr.io/prometheus-engine/prometheus:v2.41.0-gmp.5-gke.0
          args:
            - --config.file=/etc/prometheus/config.yaml
            - --export.credentials-file=/gmp/key.json
            - --storage.tsdb.path=/prometheus/data
            - --storage.tsdb.retention.time=6h
            - --web.enable-lifecycle
            - --storage.tsdb.no-lockfile
            - --web.route-prefix=/
          ports:
          - name: web
            containerPort: 9090
          readinessProbe:
            httpGet:
              path: /-/ready
              port: web
              scheme: HTTP
          volumeMounts:
            - mountPath: /etc/prometheus
              name: config
              readOnly: true
            - name: google-service-account
              mountPath: /gmp
          imagePullPolicy: Always