plugin:
  # Defines a plugin to provide a `ctrl-d` shortcut to kill the selected container in a pod.
  kill:
    # Define a mnemonic to invoke the plugin
    shortCut: Ctrl-D
    # What will be shown on the K9s menu
    description: Kill
    # Collections of views that support this shortcut. (You can use `all`)
    scopes:
    - containers
    # The command to run upon invocation. Can use Krew plugins here too!
    command: kubectl
    # Whether or not to run the command in background mode
    background: false
    # Defines the command arguments
    args:
    - --context
    - $CONTEXT
    - -n
    - $NAMESPACE
    - exec
    - -it
    - $POD
    - -c
    - $NAME
    - --
    - /bin/sh
    - -c
    - "kill -SIGINT 1"
  logs:
    # Define a mnemonic to invoke the plugin
    shortCut: Ctrl-L
    # What will be shown on the K9s menu
    description: Pod logs
    # Collections of views that support this shortcut. (You can use `all`)
    scopes:
    - po
    # The command to run upon invocation. Can use Krew plugins here too!
    command: kubectl
    # Whether or not to run the command in background mode
    background: false
    # Defines the command arguments
    args:
    - logs
    - -f
    - $NAME
    - -n
    - $NAMESPACE
    - --context
    - $CONTEXT
