apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rqlite-ro
  namespace: production
spec:
  selector:
    matchLabels:
      app: rqlite-ro
  template:
    metadata:
      labels:
        app: rqlite-ro
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      terminationGracePeriodSeconds: 5
      volumes:
        - name: data
          emptyDir:
            medium: Memory
            sizeLimit: "6Gi"
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      hostNetwork: true
      containers:
        - name: rqlite
          image: rqlite/rqlite
          args:
            - -raft-non-voter=true
            - -http-addr=0.0.0.0:4001
            - -raft-addr=0.0.0.0:4002
            - -http-adv-addr=$(PODIP):4001
            - -raft-adv-addr=$(PODIP):4002
            - -raft-snap=1024
            - -node-id=$(PODIP):4002
            - -write-queue-batch-size=1000
            - -disco-mode=consul-kv
            - -disco-config={"address":"$(CONSUL_HTTP_ADDR)","token":"$(CONSUL_HTTP_TOKEN)","scheme":"https"}
            - -raft-reap-node-timeout=24h
            - -raft-reap-read-only-node-timeout=5s
            - -on-disk
            - -on-disk-startup
            - -on-disk-path=/mnt/rqlite/rqlite.db
          resources:
            requests:
              cpu: 100m
          env:
            - name: DATA_DIR
              value: /mnt/rqlite
            - name: CONSUL_HTTP_ADDR
              valueFrom:
                secretKeyRef:
                  name: consul-address
                  key: key
            - name: CONSUL_HTTP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: consul-token
                  key: key
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: data
              mountPath: /mnt/rqlite
          ports:
            - containerPort: 4001
              name: rqlite
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /readyz
              port: 4001
            periodSeconds: 5
            timeoutSeconds: 2
            # As rqlite manages a larger and larger dataset, it can take longer
            # to be ready. This value may need to increase, depending on your experience.
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /readyz?noleader
              port: 4001
            initialDelaySeconds: 2
            timeoutSeconds: 2
            failureThreshold: 3
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
