apiVersion: v1
kind: Service
metadata:
  name: rqlite
  namespace: production
spec:
  clusterIP: None
  publishNotReadyAddresses: True
  selector:
    app: rqlite
  ports:
    - protocol: TCP
      port: 4001