apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtpengine
  namespace: production
  labels:
    component: rtpengine
spec:
  replicas: 1
  selector:
    matchLabels:
      component: rtpengine
  template:
    metadata:
      name: rtpengine
      labels:
        component: rtpengine
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: external-rtp
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 21600
      serviceAccountName: manager
      shareProcessNamespace: true
      initContainers:
        - name: init
          image: us-docker.pkg.dev/voxo-5060/voxoco/voxo-telecom:latest
          volumeMounts:
            - name: google-service-account
              mountPath: /var/secrets/google
          command: ["node", "kube-client/main.js"]
          args:
            - --assign-external-ip=true
            - --region=$(REGION)
            - --zone=$(ZONE)
            - --node-name=$(NODE_NAME)
            - --type=rtp
          env:
            - name: NODE_ENV
              value: production
            - name: MYSQL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: clusterName
            - name: ZONE
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: zone
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      containers:
        - name: rtpengine
          image: us-docker.pkg.dev/voxo-5060/voxoco/rtpengine:latest
          resources:
            requests:
              cpu: 3000m
          ports:
            - name: metrics
              containerPort: 22223
            - name: control
              containerPort: 22222
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sh", "-c", "sleep infinity" ]
          env:
            - name: TZ
              value: America/Chicago
            - name: CLOUD
              value: gcp
          volumeMounts:
            - name: usr-modules
              mountPath: /usr/lib/modules
            - name: modules
              mountPath: /lib/modules
            - name: src
              mountPath: /usr/src
          startupProbe:
            httpGet:
              path: /ping
              port: 22223
          securityContext:
            runAsUser: 0
            privileged: true
            capabilities:
              add: [ "NET_ADMIN" ]
          imagePullPolicy: Always
        - name: sidecar
          image: us-docker.pkg.dev/voxo-5060/voxoco/voxo-telecom:latest
          command: ["node", "rtpengine-sidecar/main.js"]
          ports:
            - containerPort: 42187
          env:
            - name: NODE_ENV
              value: production
            - name: SERVERID
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: serverId
            - name: MYSQL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
          securityContext:
            runAsUser: 0
            privileged: true
          imagePullPolicy: Always
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sh", "-c", "sleep infinity" ]
      volumes:
        - name: usr-modules
          hostPath:
            path: /usr/lib/modules
        - name: modules
          hostPath:
            path: /lib/modules
        - name: src
          hostPath:
            path: /usr/src
        - name: google-service-account
          secret:
            secretName: google-service-account
      imagePullSecrets:
        - name: regcred
