resources:
  - ../../base/asterisk
namespace: staging
images:
  - name: ghcr.io/voxoco/asterisk
    newName: ghcr.io/voxoco/asterisk
    newTag: dev
  - name: ghcr.io/voxoco/asterisk-sidecar
    newName: ghcr.io/voxoco/asterisk-sidecar
    newTag: dev
  - name: ghcr.io/voxoco/presence
    newName: ghcr.io/voxoco/presence
    newTag: dev
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ast
    namespace: production
  spec:
    replicas: 2
    template:
      spec:
        containers:
          - name: asterisk-sidecar
            resources:
              requests:
                cpu: 50m
          - name: presence
            resources:
              requests:
                cpu: 50m
          - name: asterisk
            resources:
              requests:
                cpu: 100m
patchesJson6902:
- target:
    group: autoscaling
    version: v1
    kind: HorizontalPodAutoscaler
    name: asterisk
  patch: |
    - op: replace
      path: /spec/minReplicas
      value: 2
