resources:
  - ../../base/db
namespace: staging
images:
  - name: ghcr.io/voxoco/innodb-cluster
    newName: ghcr.io/voxoco/innodb-cluster
    newTag: dev
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: db
    namespace: production
  spec:
    replicas: 3
    template:
      spec:
        initContainers:
          - name: init
            env:
              - name: INNODB_BUFFER_SIZE
                value: 2G
        containers:
          - name: mysql
            resources:
              requests:
                cpu: 100m
          - name: sidecar
            env:
              - name: S3_DIRECTORY
                value: dev-innodb-cluster