apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kamailio
  namespace: production
  labels:
    component: kamailio
spec:
  selector:
    matchLabels:
      component: kamailio
  template:
    metadata:
      name: kamailio
      labels:
        component: kamailio
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: external
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 2
      serviceAccountName: manager
      containers:
        - name: kamailio-sidecar
          image: ghcr.io/voxoco/kamailio-sidecar:latest
          resources:
            requests:
              cpu: 50m
          env:
            - name: TZ
              value: America/Chicago
            - name: NATSURL
              valueFrom:
                secretKeyRef:
                  name: nats-url
                  key: connectionString
            - name: MYSQL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
            - name: MYSQLKAM
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: http
              containerPort: 42184
            - name: metrics
              containerPort: 9105
          imagePullPolicy: Always
        - name: heplify
          image: sipcapture/heplify:latest
          resources:
            requests:
              cpu: 200m
          command:
            - "./heplify"
            - "-hn"
            - "$(REGION)"
            - "-hs"
            - "10.142.15.196:9060"
            - "-tcpassembly"
            - "true"
            - "-pr"
            - "5060-5061"
            - "-m"
            - "SIP"
            - "-e"
            - "-dim"
            - "OPTIONS,NOTIFY,KDMQ,REGISTER,SUBSCRIBE,PUBLISH,UPDATE"
          env:
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: clusterName
          imagePullPolicy: Always
        - name: kamailio
          image: ghcr.io/voxoco/kamailio:latest
          resources:
            requests:
              cpu: 900m
          ports:
            - name: sip1
              protocol: UDP
              containerPort: 5060
            - name: sip2
              protocol: UDP
              containerPort: 5061
            - name: sip3
              protocol: UDP
              containerPort: 8060
            - name: webrtc
              protocol: TCP
              containerPort: 8080
            - name: http
              protocol: TCP
              containerPort: 42185
          env:
            - name: TZ
              value: America/Chicago
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATSURL
              valueFrom:
                secretKeyRef:
                  name: nats-url
                  key: connectionString
            - name: MYSQL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
            - name: MYSQLKAM
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
            - name: APIBANKEY
              valueFrom:
                secretKeyRef:
                  name: apiban-key
                  key: key
            - name: DMQHOST
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: kamailioDmq
            - name: SERVERID
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: serverId
            - name: DISPATCHMODE
              value: "4"
            - name: CLOUD
              value: gcp
          securityContext:
            privileged: true
            capabilities:
              add: [ "NET_ADMIN" ]
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
