apiVersion: v1
kind: Service
metadata:
  name: omnia-api
  namespace: production
  labels:
    component: omnia-api
spec:
  ports:
    - name: http
      port: 3030
  selector:
    component: omnia-api