apiVersion: apps/v1
kind: Deployment
metadata:
  name: ast
  namespace: production
  labels:
    component: asterisk
spec:
  replicas: 1
  selector:
    matchLabels:
      component: asterisk
  template:
    metadata:
      labels:
        component: asterisk
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: internal-media
      terminationGracePeriodSeconds: 21600
      volumes:
        - name: google-service-account
          secret:
            secretName: google-service-account
        - name: astdb
          emptyDir:
            medium: Memory
            sizeLimit: "1Gi"
        - name: pbx
          emptyDir: {}
        - name: spool
          emptyDir:
            medium: Memory
            sizeLimit: "3Gi"
        - name: tmp
          emptyDir: {}
        - name: logs
          emptyDir: {}
      initContainers:
        - name: init
          image: alpine:3.16
          command: ["sh", "-c", "mkdir -p /var/log/asterisk/cel-custom /var/spool/asterisk/monitor /var/spool/asterisk/meetme /var/spool/asterisk/recording"]
          volumeMounts:
            - name: logs
              mountPath: /var/log/asterisk
            - name: spool
              mountPath: /var/spool/asterisk
      containers:
        - name: sidecar
          image: us-docker.pkg.dev/voxo-5060/voxoco/voxo-telecom:latest
          command: ["node", "asterisk-sidecar/main.js"]
          ports:
            - name: metrics
              containerPort: 3000
          env:
            - name: TZ
              value: America/Chicago
            - name: NODE_ENV
              value: production
            - name: MYSQL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
            - name: SERVERID
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: serverId
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
          volumeMounts:
            - name: google-service-account
              mountPath: /var/secrets/google
            - name: tmp
              mountPath: /tmp
          imagePullPolicy: Always
        - name: asterisk-sidecar
          image: us-docker.pkg.dev/voxo-5060/voxoco/asterisk-sidecar:latest
          ports:
            - containerPort: 4377
            - containerPort: 4573
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: TZ
              value: America/Chicago
            - name: KAMHOST
              value: kamailio-dmq
            - name: KAMSERVERID
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: serverId
            - name: NATSSERVERS
              value: "nats://nats-svc:4222"
            - name: NATSTOKEN
              valueFrom:
                secretKeyRef:
                  name: nats-token
                  key: key
            - name: MYSQL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
            - name: GCLOUD_MYSQL
              valueFrom:
                secretKeyRef:
                  name: gcloud-mysql-url
                  key: connectionString
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: clusterName
            - name: CONSUL_HTTP_ADDR
              valueFrom:
                secretKeyRef:
                  name: consul-address
                  key: key
            - name: CONSUL_HTTP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: consul-token
                  key: key
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: key
            - name: R2_WORKER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: r2-worker-api-key
                  key: key
            - name: JOBS_HTTP
              value: http://jobs:3121
            - name: DEEPGRAM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: deepgram-api-key
                  key: key
          volumeMounts:
            - name: logs
              mountPath: /var/log/asterisk
            - name: pbx
              mountPath: /var/lib/asterisk/sounds/pbx
            - name: spool
              mountPath: /var/spool/asterisk
            - name: tmp
              mountPath: /tmp
            - name: google-service-account
              mountPath: /var/secrets/google
          imagePullPolicy: Always
        - name: presence
          image: us-docker.pkg.dev/voxo-5060/voxoco/presence:latest
          ports:
            - name: metrics
              containerPort: 9102
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: TZ
              value: America/Chicago
            - name: NATSSERVERS
              value: "nats://nats-svc:4222"
            - name: NATSTOKEN
              valueFrom:
                secretKeyRef:
                  name: nats-token
                  key: key
            - name: MYSQL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
            - name: GCLOUD_MYSQL
              valueFrom:
                secretKeyRef:
                  name: gcloud-mysql-url
                  key: connectionString
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          imagePullPolicy: Always
        - name: asterisk
          image: us-docker.pkg.dev/voxo-5060/voxoco/asterisk:latest
          resources:
            requests:
              cpu: 2500m
          ports:
            - containerPort: 5080
          lifecycle:
            preStop:
              exec:
                command: [ "/var/lib/asterisk/gracefulShutdown.sh" ]
          env:
            - name: NQLITE
              value: http://nqlite:4001/db/query
            - name: TZ
              value: America/Chicago
            - name: MYSQL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: astdb
              mountPath: /var/lib/asterisk/astdb
            - name: logs
              mountPath: /var/log/asterisk
            - name: pbx
              mountPath: /var/lib/asterisk/sounds/pbx
            - name: spool
              mountPath: /var/spool/asterisk
            - name: tmp
              mountPath: /tmp
          startupProbe:
            httpGet:
              path: /asterisk/ari/asterisk/ping?api_key=asterisk:asterisk
              port: 8088
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
              - SYS_NICE
      imagePullSecrets:
        - name: regcred
