apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-agent
  namespace: production
  annotations:
    prometheus.io/port: '9102'
  labels:
    component: grafana-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      component: grafana-agent
  template:
    metadata:
      labels:
        component: grafana-agent
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      volumes:
        - name: config
          configMap:
            name: grafana-agent
      serviceAccount: manager
      containers:
        - name: grafana-agent
          image: grafana/agent:v0.24.1
          args:
            - -config.file=/etc/agent/agent.yaml
            - -enable-features=integrations-next
            - -server.http.address=0.0.0.0:80
            - -config.expand-env
          command:
            - /bin/agent
          ports:
          - containerPort: 80
            name: http-metrics
          resources:
            requests:
              cpu: 200m
          volumeMounts:
            - mountPath: /etc/agent
              name: config
          env:
            - name: USER
              value: '81451'
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: prometheus-password
                  key: key
            - name: URL
              value: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
            - name: LOGSURL
              value: https://logs-prod-us-central1.grafana.net/api/prom/push
            - name: LOGSUSER
              value: '39701'
            - name: NAME
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: clusterName
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: grafana-agent
  name: grafana-agent
  namespace: production
spec:
  clusterIP: None
  ports:
  - name: grafana-agent-http-metrics
    port: 80
    targetPort: 80
  selector:
    name: grafana-agent