apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: webrtc-kamailio
  namespace: production
spec:
  sessionAffinity:
    affinityType: "CLIENT_IP"
  timeoutSec: 40000000
  connectionDraining:
    drainingTimeoutSec: 1
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: socket-api
  namespace: production
spec:
  sessionAffinity:
    affinityType: "CLIENT_IP"
  healthCheck:
    port: 3030
    type: HTTP
    requestPath: /
  timeoutSec: 2592000
  connectionDraining:
    drainingTimeoutSec: 10
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: api
  namespace: production
spec:
  securityPolicy:
    name: "main"
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: voxo-api
  namespace: production
spec:
  timeoutSec: 25200
  healthCheck:
    port: 3050
    type: HTTP
    requestPath: /v2