apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: production
spec:
  serviceName: "mysql"
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      terminationGracePeriodSeconds: 20
      containers:
        - name: mysqld-exporter
          image: prom/mysqld-exporter
          env:
            - name: DATA_SOURCE_NAME
              value: mysqld-exporter:123456@(127.0.0.1:3306)/
          ports:
            - name: metrics
              containerPort: 9104
          args:
            - --no-collect.info_schema.innodb_cmpmem
            - --no-collect.global_variables
            - --no-collect.info_schema.innodb_metrics
            - --no-collect.info_schema.query_response_time
          imagePullPolicy: Always
        - name: sidecar
          image: ghcr.io/voxoco/orchestrator-sidecar:latest
          command: ["/bin/sh", "/mysql.sh"]
          env:
            - name: CONSUL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: consul-address
                  key: key
            - name: CONSUL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: consul-token
                  key: key
            - name: S3_BUCKET
              value: voxo-backups
            - name: DB_NAME
              value: main
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: accessKey
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: secretAccessKey
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-pw
                  key: pw
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: clusterName
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: BACKUP_INTERVAL_HOURS
              value: "4"
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: slack-webhook-url
                  key: webhook-url
          startupProbe:
            timeoutSeconds: 5
            failureThreshold: 20
            periodSeconds: 5
            exec:
              command: ["sh", "-c", "mysql -h 127.0.0.1 -p$MYSQL_ROOT_PASSWORD -s --skip-column-names -e 'SELECT meta.cluster.ready FROM meta.cluster' | grep -q 1"]
          imagePullPolicy: Always
        - name: mysql
          image: mysql:8.0.31
          args:
            - --default-authentication-plugin=mysql_native_password
            - --report-host=$(PODIP)
            - --sql-mode=NO_ENGINE_SUBSTITUTION
            - --innodb-flush-log-at-trx-commit=2
            - --max-connections=600
            - --max-allowed-packet=1073741824 # 1GB
            - --innodb-buffer-pool-size=1500M # 1.5GB
            - --event-scheduler=OFF
            - --relay-log=$(POD_NAME)-$(CLUSTER_NAME)-relay-b
            - --read-only=ON
            - --slave-skip-errors=1452,1062,1304,1032,1133,1396
            - --slave-net-timeout=4
            - --gtid-mode=ON
            - --enforce-gtid-consistency=ON
          resources:
            requests:
              cpu: 650m
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-pw
                  key: pw
            - name: MYSQL_ROOT_HOST
              value: '%'
            - name: TZ
              value: America/Chicago
            - name: DB_NAME
              value: main
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: clusterName
          ports:
            - containerPort: 3306
              name: mysql
          livenessProbe:
            timeoutSeconds: 5
            exec:
              command: ["bash", "-c", "mysqladmin -u root -p$MYSQL_ROOT_PASSWORD ping &> /dev/null"]
          startupProbe:
            timeoutSeconds: 5
            failureThreshold: 10
            periodSeconds: 5
            exec:
              command: ["bash", "-c", "mysql -h 127.0.0.1 -p$MYSQL_ROOT_PASSWORD -s --skip-column-names -e 'SELECT 1' &> /dev/null"]
          lifecycle:
            preStop:
              exec:
                command: ["bash", "-c", "sleep 10"]
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
