resources:
  - ../../base/kube-client
namespace: staging
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: kube-client
    namespace: production
  spec:
    template:
      spec:
        containers:
          - name: kube-client
            resources:
              requests:
                cpu: 50m