resources:
  - ../../base/nats
namespace: staging
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: nats
    namespace: production
  spec:
    template:
      spec:
        containers:
          - name: nats
            resources:
              requests:
                cpu: 50m