apiVersion: apps/v1
kind: Deployment
metadata:
  name: omnia-apiv2
  namespace: production
  labels:
    component: omnia-apiv2
spec:
  replicas: 1
  selector:
    matchLabels:
      component: omnia-apiv2
  template:
    metadata:
      labels:
        component: omnia-apiv2
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      volumes:
        - name: google-service-account
          secret:
            secretName: google-service-account
      containers:
        - name: omnia-apiv2
          image: us-docker.pkg.dev/voxo-5060/voxoco/omnia:latest
          command: ["deno", "task", "-c", "api/deno.jsonc", "run"]
          resources:
            requests:
              cpu: 500m
          env:
            - name: TZ
              value: America/Chicago
            - name: DEBUG
              value: "ON"
            - name: NATS_SERVERS
              value: "nats://nats-svc:4222"
            - name: NATS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: nats-token
                  key: key
            - name: MYSQL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
            - name: GCLOUD_MYSQL
              valueFrom:
                secretKeyRef:
                  name: gcloud-mysql-url
                  key: connectionString
            - name: API_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-auth-secret
                  key: authSecret
            - name: HONO_SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: hono-session-secret
                  key: key
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
          volumeMounts:
            - name: google-service-account
              mountPath: /var/secrets/google
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
