apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: jobs
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jobs
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 100