apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kamailio
  namespace: production
  labels:
    component: kamailio
spec:
  selector:
    matchLabels:
      component: kamailio
  template:
    metadata:
      name: kamailio
      labels:
        component: kamailio
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: external-sip
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 2
      serviceAccountName: manager
      initContainers:
        - name: init
          image: ghcr.io/voxoco/kube-client:latest
          volumeMounts:
            - name: config
              mountPath: /etc/kamailio/kv
            - name: google-service-account
              mountPath: /var/secrets/google
          command: ["node", "index.js"]
          args:
            - --assign-external-ip=true
            - --region=$(REGION)
            - --zone=$(ZONE)
            - --node-name=$(NODE_NAME)
            - --type=sip
            - --kamailio-consul=1
          env:
            - name: SERVERID
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: serverId
            - name: CONSUL_HTTP_ADDR
              valueFrom:
                secretKeyRef:
                  name: consul-address
                  key: key
            - name: CONSUL_HTTP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: consul-token
                  key: key
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: clusterName
            - name: ZONE
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: zone
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      containers:
        - name: kamailio-sidecar
          image: ghcr.io/voxoco/kamailio-sidecar:latest
          env:
            - name: CONSUL_HTTP_ADDR
              valueFrom:
                secretKeyRef:
                  name: consul-address
                  key: key
            - name: CONSUL_HTTP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: consul-token
                  key: key
            - name: APIBANKEY
              valueFrom:
                secretKeyRef:
                  name: apiban-key
                  key: key
            - name: TZ
              value: America/Chicago
            - name: NATSSERVERS
              value: "nats://nats-svc:4222"
            - name: NATSTOKEN
              valueFrom:
                secretKeyRef:
                  name: nats-token
                  key: key
            - name: MYSQL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: clusterName
            - name: SERVERID
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: serverId
          volumeMounts:
            - name: config
              mountPath: /etc/kamailio/kv
          ports:
            - name: metrics
              containerPort: 9105
          imagePullPolicy: Always
        - name: kamailio
          image: ghcr.io/voxoco/kamailio:latest
          resources:
            requests:
              cpu: 2300m
          ports:
            - name: webrtc
              protocol: TCP
              containerPort: 8080
          env:
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: clusterName
            - name: TZ
              value: America/Chicago
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MYSQL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
            - name: SERVERID
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: serverId
            - name: DISPATCHMODE
              value: "4"
            - name: CLOUD
              value: gcp
          volumeMounts:
            - name: config
              mountPath: /etc/kamailio/kv
          securityContext:
            privileged: true
            capabilities:
              add: [ "NET_ADMIN" ]
          imagePullPolicy: Always
      volumes:
        - name: config
          emptyDir: {}
        - name: google-service-account
          secret:
            secretName: google-service-account
      imagePullSecrets:
        - name: regcred
