kind: ConfigMap
metadata:
  name: rqlite-config
  namespace: production
apiVersion: v1
data:
  consul.json: |
    {
      "address":"$CONSUL_HTTP_ADDR",
      "token":"$CONSUL_HTTP_TOKEN",
      "scheme":"https"
    }
  backup.json: |
    {
      "version": 1,
      "type": "s3",
      "interval": "60m",
      "sub": {
        "access_key_id": "$S3_ACCESS_KEY",
        "secret_access_key": "$S3_SECRET_KEY",
        "region": "us-east-1",
        "endpoint": "https://acdb15a20b9ae99e3bca4be4e7ade9a2.r2.cloudflarestorage.com",
        "bucket": "main",
        "path": "voxo-backups/rqlite/db.rqlite.gz"
      }
    }
  restore.json: |
    {
      "version": 1,
      "type": "s3",
      "timeout": "30s",
      "continue_on_failure": true,
      "sub": {
        "access_key_id": "$S3_ACCESS_KEY",
        "secret_access_key": "$S3_SECRET_KEY",
        "region": "us-east-1",
        "endpoint": "https://acdb15a20b9ae99e3bca4be4e7ade9a2.r2.cloudflarestorage.com",
        "bucket": "main",
        "path": "voxo-backups/rqlite/db.rqlite.gz"
      }
    }